### ISSUE TITLE
How to set up the GitHub Actions workflow after changing the package manager to pnpm

### ISSUE THREAD

**Issue by Yue-plus** [LuanRoger/electron-shadcn#243]
How to set up the workflow after changing the package manager to pnpm?
将包管理器改为 pnpm 后如何设置 GitHub Actions 工作流？

I deleted the `package-lock.json` file, then used the `pnpm install` command to install the dependencies and generated the `pnpm-lock.yaml` file.
我删除了 `package-lock.json` 文件，然后使用 `pnpm install` 命令安装依赖，并且生成了 `pnpm-lock.yaml` 文件。

Now, executing 'pnpm start' can start the software normally, but the GitHub Action workflow cannot be executed correctly
现在执行 `pnpm start` 能够正常启动软件，但 GitHub Action 工作流无法正确执行。

![Image](https://github.com/user-attachments/assets/589e1879-06ea-4395-9fb6-862608570224)

I modified the workflow configuration file with reference to [pnpm documentation](https://pnpm.io/continuous-integration#github-actions):
我参照 [pnpm 文档](https://pnpm.io/zh/continuous-integration/#github-actions) 修改了工作流配置文件：

```yaml
name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm run test:unit

  test-e2e:
    timeout-minutes: 10
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [23]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm npx playwright install --with-deps
      - name: Create Executable
        run: pnpm run make
      - name: Run Playwright tests
        run: pnpm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

```

The GitHub Action workflow cannot be executed correctly:
GitHub Action 工作流无法正确执行：

![Image](https://github.com/user-attachments/assets/bb886efc-58b8-4379-9076-48804ad4180d)
